apiVersion: v1
kind: DeploymentConfig
metadata:
  name: api-staging
  namespace: vshn-demoapp1
  labels:
    app: api-staging
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources:
  triggers:
    -
      type: ImageChange
      imageChangeParams:
        automatic: false
        containerNames:
          - api-staging
        from:
          kind: ImageStreamTag
          namespace: vshn-demoapp1
          name: 'api:latest'
  replicas: 1
  test: false
  selector:
    app: api-staging
    deploymentconfig: api-staging
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api-staging
        deploymentconfig: api-staging
      annotations:
        openshift.io/container.api-staging.image.entrypoint: '["container-entrypoint","/usr/libexec/s2i/run"]'
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        -
          name: api-staging
          image: '172.30.1.1:5000/vshn-demoapp1/api:staging'
          ports:
            -
              containerPort: 9000
              protocol: TCP
          env:
            -
              name: PLAY_SECRET
              value: PLAY_SECRET_PLACEHOLDER
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext:
