stages:
  - test
  - deploy-staging
  - deploy-preprod
  - deploy-prod

test:
  image: registry.vshn.net/roland.schlaefli/docs_runner_sbt:0.13.13
  stage: test
  script:
    # test the application with SBT
    - sbt -ivy .ivy test 
    # print the disk usage of the .ivy folder
    - du -sh .ivy 
  cache:
    paths:
      - .ivy

build-dev:
  environment: api-staging
  stage: deploy-staging
  image: registry.vshn.net/roland.schlaefli/docs_runner_oc:1.3.3
  script:
    # login to the service account to get access to the CLI
    - oc login $KUBE_URL --token=$KUBE_TOKEN
    # start a new build for dev environment on every push to master
    - oc start-build api --follow 
  only:
    - master
  except:
    - tags

build-preprod:
  environment: api-preprod
  stage: deploy-preprod
  image: registry.vshn.net/roland.schlaefli/docs_runner_oc:1.3.3
  script:
    # login to the service account to get access to the CLI
    - oc login $KUBE_URL --token=$KUBE_TOKEN
    # tag the latest image as stable to trigger a deploy to preprod
    - oc tag api:latest api:stable
  only:
    - tags

build-prod:
  environment: api-prod
  stage: deploy-prod
  image: registry.vshn.net/roland.schlaefli/docs_runner_oc:1.3.3
  script:
    # login to the service account to get access to the CLI
    - oc login $KUBE_URL --token=$KUBE_TOKEN
    # tag the stable image as live to trigger a deploy to prod
    - oc tag api:stable api:live
  only:
    - tags
  when: manual
