stages:
  - build
  - deploy-staging
  - deploy-preprod
  - deploy-prod

variables:
  CLUSTER_IP_STAGING: 172.30.216.216
  OC_VERSION: 1.3.3
  SBT_CACHE: ".ivy"
  SBT_VERSION: 0.13.13

.oc: &oc
  image: appuio/gitlab-runner-oc:$OC_VERSION
  script: &oc_script
    # login to the service account to get access to the CLI
    - oc login $KUBE_URL --token=$KUBE_TOKEN
    # promote the image
    - oc tag api:$BASE_TAG api:$DEPLOY_TAG
    # update the configuration in OpenShift
    - sed -i 's|PLAY_SECRET_PLACEHOLDER|'"$PLAY_SECRET"'|g' docker/openshift/*
    - sed -i 's;api-staging;api-'$DEPLOY_ENV';g' docker/openshift/*
    - sed -i 's;api:latest;api:'$DEPLOY_TAG';g' docker/openshift/*
    - sed -i 's;'$CLUSTER_IP_STAGING';'$CLUSTER_IP';g' docker/openshift/*
    - oc replace -f docker/openshift -R
    # trigger a deployment
    - oc deploy api-$DEPLOY_ENV --latest --follow

test:
  image: appuio/gitlab-runner-sbt:$SBT_VERSION
  stage: build
  script:
    # test the application with SBT
    - sbt -ivy "$SBT_CACHE" test
    # print the disk usage of the .ivy folder
    - du -sh "$SBT_CACHE"
  cache:
    key: "$CI_PROJECT_ID"
    paths:
      - "$SBT_CACHE"

mirror:
  stage: build
  image: samueldebruyn/debian-git:latest
  script:
    # mirror the repository to GitHub
    - mkdir -p ~/.ssh
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - ssh-agent bash -c 'ssh-add <(echo "$DEPLOY_KEY"); git push --force git@github.com:appuio/shop-example-api.git origin/master:master; git push --force git@github.com:appuio/shop-example-api.git --tags'
  only:
    - master
  allow_failure: true

build-staging:
  <<: *oc
  environment: api-staging
  stage: deploy-staging
  script:
    # login to the service account to get access to the CLI
    - oc login $KUBE_URL --token=$KUBE_TOKEN
    # start a new build for staging environment on every push to master
    - oc start-build api --follow
    # update the configuration in openshift
    - sed -i 's|PLAY_SECRET_PLACEHOLDER|'"$PLAY_SECRET"'|g' docker/openshift/*
    - oc replace -f docker/openshift -R
    # trigger a deployment
    - oc deploy api-staging --latest --follow
  only:
    - master
  except:
    - tags

build-preprod:
  <<: *oc
  environment: api-preprod
  stage: deploy-preprod
  only:
    - tags
  variables:
    BASE_TAG: latest
    CLUSTER_IP: 172.30.232.198
    DEPLOY_ENV: preprod
    DEPLOY_TAG: stable

build-prod:
  <<: *oc
  environment: api-prod
  stage: deploy-prod
  only:
    - tags
  when: manual
  variables:
    BASE_TAG: stable
    CLUSTER_IP: 172.30.249.91
    DEPLOY_ENV: prod
    DEPLOY_TAG: live
