stages:
  - build
  - deploy-staging
  - deploy-preprod
  - deploy-prod

variables:
  CLUSTER_IP_STAGING: 172.30.216.216
  CLUSTER_IP_PREPROD: 172.30.232.198
  CLUSTER_IP_PROD: 172.30.249.91
  OC_VERSION: 1.3.3
  SBT_CACHE: ".ivy"
  SBT_VERSION: 0.13.13

test:
  image: appuio/gitlab-runner-sbt:$SBT_VERSION
  stage: build
  script:
    # test the application with SBT
    - sbt -ivy "$SBT_CACHE" test 
    # print the disk usage of the .ivy folder
    - du -sh "$SBT_CACHE"
  cache:
    key: "$CI_PROJECT_ID"
    paths:
      - "$SBT_CACHE"
      
mirror:
  stage: build
  image: samueldebruyn/debian-git:latest
  script:
    # mirror the repository to GitHub
    - mkdir -p ~/.ssh
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - ssh-agent bash -c 'ssh-add <(echo "$DEPLOY_KEY"); git push --force git@github.com:appuio/shop-example-api.git origin/master:master; git push --force git@github.com:appuio/shop-example-api.git --tags'
  only:
    - master
  allow_failure: true

build-staging:
  environment: api-staging
  stage: deploy-staging
  image: appuio/gitlab-runner-oc:$OC_VERSION
  script:
    # login to the service account to get access to the CLI
    - oc login $KUBE_URL --token=$KUBE_TOKEN
    # start a new build for staging environment on every push to master
    - oc start-build api --follow 
    # update the configuration in openshift
    - sed -i 's|PLAY_SECRET_PLACEHOLDER|'"$PLAY_SECRET"'|g' docker/openshift/*
    - oc replace -f docker/openshift -R
    # trigger a deployment
    - oc deploy api-staging --latest --follow
  only:
    - master
  except:
    - tags

build-preprod:
  environment: api-preprod
  stage: deploy-preprod
  image: appuio/gitlab-runner-oc:$OC_VERSION
  script:
    # login to the service account to get access to the CLI
    - oc login $KUBE_URL --token=$KUBE_TOKEN
    # tag the latest image as stable
    - oc tag api:latest api:stable
    # update the configuration in OpenShift
    - sed -i 's|PLAY_SECRET_PLACEHOLDER|'"$PLAY_SECRET"'|g' docker/openshift/*
    - sed -i 's;api-staging;api-preprod;g' docker/openshift/*
    - sed -i 's;api:latest;api:stable;g' docker/openshift/*
    - sed -i 's;'$CLUSTER_IP_STAGING';'$CLUSTER_IP_PREPROD';g' docker/openshift/*
    - oc replace -f docker/openshift -R
    # trigger a deployment
    - oc deploy api-preprod --latest --follow
  only:
    - tags

build-prod:
  environment: api-prod
  stage: deploy-prod
  image: appuio/gitlab-runner-oc:$OC_VERSION
  script:
    # login to the service account to get access to the CLI
    - oc login $KUBE_URL --token=$KUBE_TOKEN
    # tag the stable image as live
    - oc tag api:stable api:live
    # update the configuration in OpenShift
    - sed -i 's|PLAY_SECRET_PLACEHOLDER|'"$PLAY_SECRET"'|g' docker/openshift/*
    - sed -i 's;api-staging;api-prod;g' docker/openshift/*
    - sed -i 's;api:latest;api:live;g' docker/openshift/*
    - sed -i 's;'$CLUSTER_IP_STAGING';'$CLUSTER_IP_PROD';g' docker/openshift/*
    - oc replace -f docker/openshift -R
    # trigger a deployment
    - oc deploy api-prod --latest --follow
  only:
    - tags
  when: manual
