version: "2.1"
services:
  api:
    image: shop-example-api
    environment:
      PLAY_SECRET: abcdefgh
      DB_DATABASE: play
      DB_HOSTNAME: api-db
      DB_PASSWORD: play
      DB_USERNAME: play
      ORDERS_ENDPOINT: http://orders:8080/api/v1
      USERS_ENDPOINT: http://users:4000/api/v1
    ports:
      - "9000:9000"

  api-db:
    image: postgres:9.5-alpine
    environment:
      POSTGRES_USER: play
      POSTGRES_PASSword: play
    ports:
      - "5432:5432"
